port 1194
proto udp
dev tun

ca /data/pki/ca.crt
cert /data/pki/issued/server.crt
key /data/pki/private/server.key
dh /data/pki/dh.pem
crl-verify /data/pki/crl.pem
tls-crypt /data/pki/tc.key

server 10.8.0.0 255.255.255.0
topology subnet

ifconfig-pool-persist /data/ipp.txt
client-config-dir /data/ccd

push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

keepalive 10 120
cipher AES-256-GCM
data-ciphers AES-256-GCM:AES-128-GCM

persist-key
persist-tun

status /data/logs/openvpn-status.log 10
log-append /data/logs/openvpn.log
verb 3

explicit-exit-notify 1
